/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank.project;

import javax.swing.DefaultComboBoxModel;
import java.util.Random;
import java.sql.*;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author soodm
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    String[] year = {"Select Year", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960",
        "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970",
        "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980",
        "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990",
        "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000",
        "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010",
        "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021"};

    String[] month = {"Select Month", "January", "February", "March", "April", "May", "June", "July",
        "August", "September", "October", "November", "December"};

    String[] day_31 = {"Select Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
        "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
        "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"};

    String[] day_30 = {"Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
        "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
        "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"};

    String[] day_28 = {"Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
        "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
        "21", "22", "23", "24", "25", "26", "27", "28"};

    String[] day_29 = {"Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
        "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
        "21", "22", "23", "24", "25", "26", "27", "28", "29"};

    private boolean checkLeapYear(int y) {
        boolean isLeap = false;
        if (((y % 4 == 0) && (y % 100 != 0)) || (y % 400 == 0)) {
            isLeap = true;
        }
        return isLeap;
    }

    public Register() {
        initComponents();
        this.setTitle("Register New Account");
        yearCB.setModel(new DefaultComboBoxModel(year));
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBtnGrp = new javax.swing.ButtonGroup();
        marriageBtnGrp = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        userTypeCB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        nextBtnPanel1 = new javax.swing.JButton();
        confirmPasswordTF = new javax.swing.JPasswordField();
        clearBtnPanel1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        showHideCheckBox = new javax.swing.JCheckBox();
        showHideCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        firstnameTF = new javax.swing.JTextField();
        middlenameTF = new javax.swing.JTextField();
        lastnameTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        yearCB = new javax.swing.JComboBox<>();
        monthCB = new javax.swing.JComboBox<>();
        dayCB = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fathernameTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        occupationTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        contactTF = new javax.swing.JTextField();
        nextBtnPanel2 = new javax.swing.JButton();
        clearBtnPanel2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        marriageNoRB = new javax.swing.JRadioButton();
        marriageYesRB = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        maleRB = new javax.swing.JRadioButton();
        femaleRB = new javax.swing.JRadioButton();
        othersRB = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        c_address = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        p_address = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        registerBtnPanel3 = new javax.swing.JButton();
        clearBtnPanel3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(794, 650));
        setResizable(false);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        userTypeCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        userTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User Type", "Customer", "Employee" }));
        userTypeCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                userTypeCBItemStateChanged(evt);
            }
        });
        userTypeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTypeCBActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("User Name");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Password");

        usernameTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        usernameTF.setToolTipText("Enter your USERNAME here");
        usernameTF.setEnabled(false);
        usernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTFActionPerformed(evt);
            }
        });

        passwordTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        passwordTF.setToolTipText("Enter Password");
        passwordTF.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Confirm Password");

        nextBtnPanel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nextBtnPanel1.setText("Next");
        nextBtnPanel1.setEnabled(false);
        nextBtnPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnPanel1ActionPerformed(evt);
            }
        });

        confirmPasswordTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        confirmPasswordTF.setToolTipText("Enter Password");
        confirmPasswordTF.setEnabled(false);
        confirmPasswordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordTFActionPerformed(evt);
            }
        });

        clearBtnPanel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        clearBtnPanel1.setText("Clear");
        clearBtnPanel1.setEnabled(false);
        clearBtnPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnPanel1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register a New Account");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Email");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Select User Type");

        emailTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        emailTF.setToolTipText("Enter your Email here");
        emailTF.setEnabled(false);

        showHideCheckBox.setToolTipText("Select to SHOW/HIDE password");
        showHideCheckBox.setEnabled(false);
        showHideCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                showHideCheckBoxStateChanged(evt);
            }
        });

        showHideCheckBox1.setToolTipText("Select to SHOW/HIDE password");
        showHideCheckBox1.setEnabled(false);
        showHideCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                showHideCheckBox1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showHideCheckBox)
                    .addComponent(showHideCheckBox1))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showHideCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showHideCheckBox1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(passwordTF, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(emailTF, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(usernameTF, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(userTypeCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, 227, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(269, 269, 269))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nextBtnPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(227, 227, 227))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addComponent(clearBtnPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(206, 206, 206))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(emailTF, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(passwordTF, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(confirmPasswordTF, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearBtnPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(nextBtnPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(380, 380, 380))
        );

        jTabbedPane1.addTab("1. User Information", jPanel1);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Name");

        firstnameTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        firstnameTF.setToolTipText("First Name");

        middlenameTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        middlenameTF.setToolTipText("Middle Name");

        lastnameTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lastnameTF.setToolTipText("Last Name");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("DOB");

        yearCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        yearCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Year" }));
        yearCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearCBItemStateChanged(evt);
            }
        });
        yearCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearCBActionPerformed(evt);
            }
        });

        monthCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        monthCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month" }));
        monthCB.setEnabled(false);
        monthCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthCBItemStateChanged(evt);
            }
        });
        monthCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthCBActionPerformed(evt);
            }
        });

        dayCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dayCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Day" }));
        dayCB.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Gender");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Married");

        fathernameTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Father/Husband Name");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Occupation");

        occupationTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Contact Number");

        contactTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        nextBtnPanel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nextBtnPanel2.setText("Next");
        nextBtnPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnPanel2ActionPerformed(evt);
            }
        });

        clearBtnPanel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        clearBtnPanel2.setText("Clear");
        clearBtnPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnPanel2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Personal Information");

        marriageBtnGrp.add(marriageNoRB);
        marriageNoRB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        marriageNoRB.setText("No");

        marriageBtnGrp.add(marriageYesRB);
        marriageYesRB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        marriageYesRB.setText("Yes");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(marriageYesRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(marriageNoRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(marriageYesRB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(marriageNoRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        genderBtnGrp.add(maleRB);
        maleRB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        maleRB.setText("Male");
        maleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRBActionPerformed(evt);
            }
        });

        genderBtnGrp.add(femaleRB);
        femaleRB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        femaleRB.setText("Female");
        femaleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRBActionPerformed(evt);
            }
        });

        genderBtnGrp.add(othersRB);
        othersRB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        othersRB.setText("Others");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(maleRB, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(femaleRB, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(othersRB, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleRB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(femaleRB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(othersRB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(254, 254, 254))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstnameTF)
                                    .addComponent(yearCB, 0, 109, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(middlenameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lastnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(monthCB, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(dayCB, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(fathernameTF)
                            .addComponent(occupationTF)
                            .addComponent(contactTF)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nextBtnPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(clearBtnPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(205, 205, 205))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(middlenameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearCB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthCB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayCB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fathernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(occupationTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearBtnPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(nextBtnPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(194, 194, 194))
        );

        jTabbedPane1.addTab("2. Personal Information", jPanel2);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Address Information");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Corresponding Address");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Permanent Address");

        c_address.setColumns(20);
        c_address.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        c_address.setRows(5);
        jScrollPane1.setViewportView(c_address);

        p_address.setColumns(20);
        p_address.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        p_address.setRows(5);
        jScrollPane2.setViewportView(p_address);

        jCheckBox1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jCheckBox1.setText("Same As Corresponding Address");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        registerBtnPanel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        registerBtnPanel3.setText("Register");
        registerBtnPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnPanel3ActionPerformed(evt);
            }
        });

        clearBtnPanel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        clearBtnPanel3.setText("Clear");
        clearBtnPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnPanel3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(registerBtnPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(clearBtnPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(290, 290, 290))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearBtnPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(registerBtnPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(200, 200, 200))
        );

        jTabbedPane1.addTab("3.Address Information", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtnPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnPanel1ActionPerformed
        userTypeCB.setSelectedIndex(0);
        usernameTF.setText("");
        emailTF.setText("");
        passwordTF.setText("");
        confirmPasswordTF.setText("");
        showHideCheckBox.setSelected(false);
        showHideCheckBox1.setSelected(false);
    }//GEN-LAST:event_clearBtnPanel1ActionPerformed

    private void showHideCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_showHideCheckBoxStateChanged
        if (showHideCheckBox.isSelected()) {
            passwordTF.setEchoChar((char) 0);
        } else {
            passwordTF.setEchoChar('*');
        }
    }//GEN-LAST:event_showHideCheckBoxStateChanged

    private void showHideCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_showHideCheckBox1StateChanged
        if (showHideCheckBox1.isSelected()) {
            confirmPasswordTF.setEchoChar((char) 0);
        } else {
            confirmPasswordTF.setEchoChar('*');
        }
    }//GEN-LAST:event_showHideCheckBox1StateChanged

    private void userTypeCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_userTypeCBItemStateChanged
        if (userTypeCB.getSelectedIndex() != 0) {
            usernameTF.setEnabled(true);
            emailTF.setEnabled(true);
            passwordTF.setEnabled(true);
            confirmPasswordTF.setEnabled(true);
            showHideCheckBox.setEnabled(true);
            showHideCheckBox1.setEnabled(true);
            nextBtnPanel1.setEnabled(true);
            clearBtnPanel1.setEnabled(true);
        } else {
            usernameTF.setEnabled(false);
            emailTF.setEnabled(false);
            passwordTF.setEnabled(false);
            confirmPasswordTF.setEnabled(false);
            showHideCheckBox.setEnabled(false);
            showHideCheckBox1.setEnabled(false);
            nextBtnPanel1.setEnabled(false);
            clearBtnPanel1.setEnabled(false);
        }
    }//GEN-LAST:event_userTypeCBItemStateChanged

    private void nextBtnPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnPanel1ActionPerformed
        if (Arrays.toString(passwordTF.getPassword()).equals("") || emailTF.getText().equals("") || usernameTF.getText().equals("") || Arrays.toString(confirmPasswordTF.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(rootPane, "All Fields are Mandatory");
        } else {
            String regex ="^(.+)@(.+)$";
            Pattern pattern = Pattern.compile(regex);
            Matcher match = pattern.matcher(emailTF.getText());
            if(match.matches()==false)
            {
             JOptionPane.showMessageDialog(rootPane, "Please enter valid Email Address.", "Warning", JOptionPane.WARNING_MESSAGE);
               
            }
            else{
            String p = Arrays.toString(passwordTF.getPassword());
            String c = Arrays.toString(confirmPasswordTF.getPassword());
            if(!(p.equals(c))){
                JOptionPane.showMessageDialog(rootPane, "Password not matches with confirm password.", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                String username = usernameTF.getText();

                String dburl = "jdbc:oracle:thin:@localhost:1521:xe";
                String user = "SYSTEM";
                String pass = "1234";

                try {
                    Connection con = DriverManager.getConnection(dburl, user, pass);
                    System.out.println("connected successfully");
                    PreparedStatement ps = con.prepareStatement("select * from BANK_CE_TABLE where username='" + username + "'");

                    ResultSet rs = ps.executeQuery();

                    if (rs.next()) {
                        JOptionPane.showMessageDialog(this, "Username Already exists");
                        usernameTF.setText("");
                        usernameTF.requestFocus();

                    } else {

                        jTabbedPane1.setEnabledAt(1, true);
                        jTabbedPane1.setSelectedIndex(1);
                    }
                } catch (SQLException ex) {
                    System.out.println("Error");
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            }
        }

    }//GEN-LAST:event_nextBtnPanel1ActionPerformed

    private void nextBtnPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnPanel2ActionPerformed
        if (firstnameTF.getText().equals("") || lastnameTF.getText().equals("") || fathernameTF.getText().equals("") || occupationTF.getText().equals("") || contactTF.getText().equals("")||yearCB.getSelectedIndex()==0||monthCB.getSelectedIndex()==0||dayCB.getSelectedIndex()==0||genderBtnGrp.getSelection()==null||marriageBtnGrp.getSelection()==null) 
        {
           JOptionPane.showMessageDialog(rootPane, "All Fields are Mandatory");
        }
        else
        {
            String regex= "^[1-9][0-9]{9}$";
            Pattern pattern = Pattern.compile(regex);
            Matcher match = pattern.matcher(contactTF.getText());
            if(match.matches()==false)
            {
                
                
                JOptionPane.showMessageDialog(rootPane, "Pleaase Enter 10 digit Valid Contact number");
        
            }
            else
            {
        jTabbedPane1.setEnabledAt(2, true);
     jTabbedPane1.setSelectedIndex(2);
            }
            }
    }//GEN-LAST:event_nextBtnPanel2ActionPerformed

    private void clearBtnPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnPanel2ActionPerformed
        firstnameTF.setText("");
        middlenameTF.setText("");
        lastnameTF.setText("");
        yearCB.setSelectedIndex(0);
        monthCB.setSelectedIndex(0);
        dayCB.setSelectedIndex(0);
        fathernameTF.setText("");
        occupationTF.setText("");
        contactTF.setText("");
        genderBtnGrp.clearSelection();
        marriageBtnGrp.clearSelection();

    }//GEN-LAST:event_clearBtnPanel2ActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        if (jCheckBox1.isSelected()) {
            String str = c_address.getText();
            p_address.setText(str);
            p_address.setEditable(false);
        } else {
            p_address.setText("");
            p_address.setEditable(true);
        }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void registerBtnPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnPanel3ActionPerformed
if (c_address.getText().equals("") || p_address.getText().equals("")) 
        {
           JOptionPane.showMessageDialog(rootPane, "All Fields are Mandatory");
        }
else
{
        String dburl = "jdbc:oracle:thin:@localhost:1521:xe";
        String user = "SYSTEM";
        String pass = "1234";

        try {
            String usertype = userTypeCB.getSelectedItem().toString();
            String username = usernameTF.getText();
            String email = emailTF.getText();
            String password = passwordTF.getText();
            String name = firstnameTF.getText() + " " + middlenameTF.getText() + " " + lastnameTF.getText();
            String dob = yearCB.getSelectedItem().toString() + "/" + monthCB.getSelectedItem().toString() + "/" + dayCB.getSelectedItem().toString();
            maleRB.setActionCommand("Male");
            femaleRB.setActionCommand("Female");
            String gender = genderBtnGrp.getSelection().getActionCommand();
            marriageYesRB.setActionCommand("Yes");
            marriageNoRB.setActionCommand("No");
            String married = marriageBtnGrp.getSelection().getActionCommand();
            String fname = fathernameTF.getText();
            String occupation = occupationTF.getText();
            String contact_no = contactTF.getText();
            String correspondence_address = c_address.getText();
            String permanent_address = p_address.getText();
            Connection con = DriverManager.getConnection(dburl, user, pass);
            System.out.println("connected successfully");
            Statement st = con.createStatement();

            String query1 = "INSERT INTO BANK_CE_TABLE"
                    + " (USERNAME,NAME,DOB,GENDER,MARRIED,FATHER_NAME,OCCUPATION,CONTACT_NO,P_ADDRESS,C_ADDRESS,EMAIL,USER_TYPE,PASSWORD)"
                    + "VALUES('" + username + "','" + name + "','" + dob + "','" + gender + "','" + married + "','" + fname + "','" + occupation + "','" + contact_no + "','" + permanent_address + "','" + correspondence_address + "','" + email + "','" + usertype + "','" + password + "')";

            // record added.
            String msg = "Your Account Number is ";
            boolean flag = true;
            while (flag == true) {
                try {
                    Random rnd = new Random();
                    int number = rnd.nextInt(999999999);
                    String account_no = String.format("%09d", number);
                    System.out.println(account_no);
                    msg += account_no;
                    String balance = "0";
                    String query2 = "INSERT INTO BANK_ACCT_TABLE"
                            + " (USERNAME,ACCT_NO,BALANCE)"
                            + "VALUES('" + username + "','" + account_no + "','" + balance + "')";
                    st.executeUpdate(query2);
                    flag = false;
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    //System.out.println("Account no already exists");
                }
            }
            st.executeUpdate(query1);
            System.out.println("records added");
            con.close();

            JOptionPane.showMessageDialog(rootPane, msg, "Account No.", HEIGHT);
            this.dispose();
            new Login().setVisible(true);
        } catch (SQLIntegrityConstraintViolationException ex) {
            String msg = "User Name already exists.";
            JOptionPane.showMessageDialog(rootPane, msg, "UserName Error", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException ex) {
            System.out.println("Error");
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }

}
    }//GEN-LAST:event_registerBtnPanel3ActionPerformed

    private void clearBtnPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnPanel3ActionPerformed
        c_address.setText("");
        p_address.setText("");
        jCheckBox1.setSelected(false);
    }//GEN-LAST:event_clearBtnPanel3ActionPerformed

    private void confirmPasswordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordTFActionPerformed

    private void yearCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearCBItemStateChanged
        int index = yearCB.getSelectedIndex();
        monthCB.setEnabled(false);
        monthCB.setModel(new DefaultComboBoxModel(new String[]{"Select Month"}));
        if (index != 0) {
            monthCB.setEnabled(true);
            monthCB.setModel(new DefaultComboBoxModel(month));
        }
    }//GEN-LAST:event_yearCBItemStateChanged

    private void monthCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthCBItemStateChanged
        int index = monthCB.getSelectedIndex();
        dayCB.setEnabled(false);
        dayCB.setModel(new DefaultComboBoxModel(new String[]{"Select Day"}));
        if (index != 0) {
            dayCB.setEnabled(true);
            boolean res = checkLeapYear(Integer.parseInt((String) yearCB.getSelectedItem()));
            if (index == 2) {
                if (res == true) {
                    dayCB.setModel(new DefaultComboBoxModel(day_29));
                } else {
                    dayCB.setModel(new DefaultComboBoxModel(day_28));
                }
            }
            if (index == 1 || index == 3 || index == 5 || index == 7 || index == 8 || index == 10 || index == 12) {
                dayCB.setModel(new DefaultComboBoxModel(day_31));
            }
            if (index == 4 || index == 6 || index == 9 || index == 11) {
                dayCB.setModel(new DefaultComboBoxModel(day_30));
            }
        }
    }//GEN-LAST:event_monthCBItemStateChanged

    private void userTypeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTypeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTypeCBActionPerformed

    private void usernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTFActionPerformed

    private void yearCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearCBActionPerformed

    private void femaleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRBActionPerformed

    private void maleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRBActionPerformed

    private void monthCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea c_address;
    private javax.swing.JButton clearBtnPanel1;
    private javax.swing.JButton clearBtnPanel2;
    private javax.swing.JButton clearBtnPanel3;
    private javax.swing.JPasswordField confirmPasswordTF;
    private javax.swing.JTextField contactTF;
    private javax.swing.JComboBox<String> dayCB;
    private javax.swing.JTextField emailTF;
    private javax.swing.JTextField fathernameTF;
    private javax.swing.JRadioButton femaleRB;
    private javax.swing.JTextField firstnameTF;
    private javax.swing.ButtonGroup genderBtnGrp;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastnameTF;
    private javax.swing.JRadioButton maleRB;
    private javax.swing.ButtonGroup marriageBtnGrp;
    private javax.swing.JRadioButton marriageNoRB;
    private javax.swing.JRadioButton marriageYesRB;
    private javax.swing.JTextField middlenameTF;
    private javax.swing.JComboBox<String> monthCB;
    private javax.swing.JButton nextBtnPanel1;
    private javax.swing.JButton nextBtnPanel2;
    private javax.swing.JTextField occupationTF;
    private javax.swing.JRadioButton othersRB;
    private javax.swing.JTextArea p_address;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JButton registerBtnPanel3;
    private javax.swing.JCheckBox showHideCheckBox;
    private javax.swing.JCheckBox showHideCheckBox1;
    private javax.swing.JComboBox<String> userTypeCB;
    private javax.swing.JTextField usernameTF;
    private javax.swing.JComboBox<String> yearCB;
    // End of variables declaration//GEN-END:variables
}
